version: '3.8'

services:
  bot:
    build: .
    container_name: proj_n_bot
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    networks:
      - my_network
    ports:
      - "5001:5000"
    command: supervisord -c /etc/supervisor/conf.d/supervisord.conf
    
networks:
  my_network:
    external: true
